# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Minimalism"
license = "MIT"
licenselink = "https://github.com/joebartels/hugo-minimalism/blob/master/LICENSE.md"
description = ""
homepage = "http://joebartels.github.io.com/hugo-minimalism"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "joseph bartels"
  homepage = "https://joebartels.github.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
